### ISSUE TITLE
Using SVG pictures for faster load ?

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic-ui#10]
I think we should consider using svg pictures for all the icons and others pictures !

This is mainly to be more lightweight and fast !

Or if we could get ride of pictures it would be also great.

Another idea would be to, for example, use an icon set like Font awesome or better ?

**Comment by bfkelsey** [comment]
It is currently using the [Material Icon](https://material.io/icons/) set.

**Comment by jooola** [comment]
Ah ok didn't noticed this, but why keeping the themed assets from the old UI ? If we start from scratch we could not use those and if we want more themes simply rebuild some that looks like the old ones ?

**Comment by bfkelsey** [comment]
I didn't really look through them just copied the folder over and started using what I needed.

**Comment by bfkelsey** [comment]
We could probably delete most of them and just leave the logo images though. I don't really know what is all in there.

**Comment by bfkelsey** [comment]
This is no longer an issue
