### ISSUE TITLE
Add I18n to start translating

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic-ui#16]
IMO we could start thinking at internationalization : 

If we translate strings by strings ( each time you add one ) it will be easier than translating a huge pack of strings.

And I don't think it worth keeping the old translations ( maybe cherry pick some strings ).

Secondly we currently have problems with bad escaping in the current UI. So we should think at somehting that isolate each string well !

**Comment by bfkelsey** [comment]
It looks like angular has some built in tools for this https://angular.io/guide/i18n

**Comment by jooola** [comment]
... Sadly I won't be able to implement the i18n system cleanly...
I suggest you add the i18n system and I add and translate all the strings we currenlyt have ?
I mean I can create the translation files and add all the Id's but I cannot implement the main system.
