### ISSUE TITLE
Remove unused pictures

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic-ui#2]
Some pictures will never be used and could be removed ( better start with less and cleaner than too much and a mess ).

This pictures mainly are in the themes folders : 
- jamstash ( we aren't providing attached app within airsonic we use the docs )
- donate ( We don't ask money )
- android
- apps
- paypal

**Comment by bfkelsey** [comment]
Could you submit a Pr for this? Thanks

**Comment by jooola** [comment]
I will later !

Le 4 septembre 2017 00:52:41 GMT+02:00, Ben Kelsey <notifications@github.com> a écrit :
>Could you submit a Pr for this? Thanks
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/airsonic/airsonic-ui/issues/2#issuecomment-326836708

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
