### ISSUE TITLE
Login don't update profile dropdown menu with username

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic-ui#27]
signing in don't update profile dropdown menu with user name, at least not directly after the login, after refreshing the page everything is just fine

**Comment by jooola** [comment]
Right after login :
![image](https://user-images.githubusercontent.com/19195485/31589203-0c9f52ae-b1fe-11e7-82d1-95a1300176d3.png)

**Comment by bfkelsey** [comment]
I don't see this issue in the current version. Feel free to reopen if you can repeat it.
