### ISSUE TITLE
Live preview

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic-ui#3]
What do you think of getting a live preview of the current work ?

at airsonic.github.io/demo/airsonic-ui ?

**Comment by bfkelsey** [comment]
Yeah that would be great. I have a basic player setup now that I can hopefully push this weekend and then I will publish it.

**Comment by biconou** [comment]
I am eager to see any screenshot. Just paste one here ?

**Comment by bfkelsey** [comment]
![Albums View](https://user-images.githubusercontent.com/131458/30007233-05be91bc-90bf-11e7-9fed-41d828f4e723.png)
![Single Album View](https://user-images.githubusercontent.com/131458/30007236-0bb02130-90bf-11e7-8056-9403cc294705.png)

**Comment by bfkelsey** [comment]
Now deployed at https://airsonic.github.io/airsonic-ui/
