### ISSUE TITLE
Which translation system shoudl we use ?

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic-ui#51]
I'm asking myself which language system we should use ?

Because the angular [embed i18n](https://angular.io/guide/i18n) system looks not really dynamic.

Why not something [like this](https://github.com/ngx-translate/core) that ships services and all the tools to switch the language of the App.

Also I'm gonna add our translations files on Transifex so we can translate everything properly as we grow and cherry pick most of the string from current airsonic UI.

@bfkelsey any thoughts ?

**Comment by bfkelsey** [comment]
ngx-translate looks to be a lot more powerful then the built in translation tools.

**Comment by jooola** [comment]
Just merged a PR with the new ngx-translation system and it work really fine !
