### ISSUE TITLE
Rethink auth service 

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic-ui#54]
The current state of airsonic ( master branch ) is broken.

Here is the problem:
- Page loads and tries to fetch the translation files via the HTTPClient (ngx-translate)
- The HTTP request faces the basic auth system `if has not user => route to /login`
- So the HTTP request never get the <lang>.json files present in /assets/i18n/*
- Results in a broken system

If I disable the `translate.setDefaultLang('en');` the translation service don't work at all.

So since our UI will handle a way more complex system, I think we really need to use something like [Guards](https://angular.io/guide/router#milestone-5-route-guards).

Using guards will give us the possibility to allow some component access (based on the routes) depending on the permissions the user have.
This involves to load the permissions by loading them at login ([using the getUser Api call ](http://www.subsonic.org/pages/inc/api/examples/user_example_1.xml))
Loading permissions at login will also allow us to verify if user really exists ( instead of simply generating token+salt and trying to go the the main (home) component and face a HTTP 401), This gives us also a better way to handle errors.

So the guards will allow or not route depending on the users permissions using CanActivate. This will allow us to let everyone to fetch the assets via HTTP.

Other solution regarding the translation service would be not to load over HTTP.

So @bfkelsey, I would like some of your time so we discuss a bit about his, the vulnerabilities of this solutions, any thoughts ?

**Comment by jooola** [comment]
After trying to build a huge auth system, I finally understood what happens in the HTTP interceptor in shared/auth/AuthInterceptor.ts .
So I fixed the translation problem, which don't really match my issue above... Weird...

Still I think we are gonna need this system since it way more powerful than the current one and we need a fine grained auth system, since user can access to different roles depending on they privileges.

Also, since we are gonna have shared playlists we will need to allow some guest users to use the app without being logged in. ( Well this is one of the many use case )

**Comment by bfkelsey** [comment]
It looks like this can be fixed by just not setting a default and changing en.json to en-US.json. The translationService will then pull for en-US.json by default. That seemed to fix the runtime errors that I was seeing
