### ISSUE TITLE
information

### ISSUE THREAD

**Issue by pwepwe973** [airsonic/airsonic-ui#69]
Bonjour

L’ancienne interface va totalement disparaître?

car j'aimais bien l’allure de l’ancienne je trouve qu'elle faisais site d’écoute en streaming hyper professionnel.
la nouvelle je la trouve trop simpliste 

Cordialement

**Comment by jooola** [comment]
Mais c'est vraiment une idée sur le long terme, l'applications web actuelle n'est vraiment pas complete, et tant qu'il manque des fonctionnalités nous n'allons pas remplacer l'ancienne avec celle ci
