### ISSUE TITLE
Don't use pictures for albums without cover art but somehting more lightweight

### ISSUE THREAD

**Issue by jooola** [airsonic/airsonic-ui#8]
I suggest we remove the system that generates picture with album name and artist.
This loads a huge amount of picture.

We could simply use svg model and change the artist and album name following the model.
Or more lightweight don't use a picture at all ! simply css and some js !

Also the pictures are 160x160 big, so this isn't really scalable ...

**Comment by bfkelsey** [comment]
The size is only 2.7kb for the generated images and between 1 and 10kb for the rest. It would be nice if the api had some kind of boolean if an image was present. Then we could generate a placeholder image client-side.

**Comment by bfkelsey** [comment]
This is no longer an issue
